import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "@/components/ui/toaster";
import Incentives from "@/components/Incentives";
import Header from "@/components/Header"; 

export const metadata: Metadata = {
  title: "toannv",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      {/* Include a suppressHydrationWarning to avoid React hydration mismatch warnings */}
      <body className="min-h-screen antialiased">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Header />
          {children}
          <Incentives />
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
